--Elaborar o Script de criação do BD Locadora com todas suas tabelas, atributos, PKs, FKs e com no mínimo 10 inserts em cada tabela (20 nas associativas).
--Elabore as seguintes consultas:
-- - Que liste todos os autores e os filmes que atuaram.
-- - Que relacione todos os clientes com os filmes locados.
-- - Que mostre todos os filmes e seus generos e categorias.
-- - Que liste os filmes locados em 2026.
-- - Que mostre os 2 filmes mais locados no ano de 2025.
-- - Que mostre o Gênero mais locado.
-- - Que conte os clientes por estados.


create database LOCADORA

create table PROFISSAO
(
	COD_PROF INTEGER PRIMARY KEY NOT NULL IDENTITY,
	NOME VARCHAR(60),
)

create table ENDERECO
(
	COD_END INTEGER PRIMARY KEY NOT NULL IDENTITY,
	LOGRADOURO VARCHAR(40),
	TIPO_LOG VARCHAR(40),
	COMPLEMENTO VARCHAR(20),
	CIDADE VARCHAR(60),
	UF CHAR(2),
	CEP CHAR(8),
	NUMERO VARCHAR(10),
	BAIRRO VARCHAR(60)
)

CREATE TABLE CLIENTE
(
	COD_CLI INTEGER PRIMARY KEY NOT NULL IDENTITY,
	CPF CHAR(11),
	NOME VARCHAR(60),
	TELEFONE VARCHAR(10),
	FK_COD_PROF INTEGER,
	FOREIGN KEY (FK_COD_PROF) REFERENCES PROFISSAO(COD_PROF)
)

CREATE TABLE CLI_ENDERECO
(
	FK_COD_END INTEGER NOT NULL,
	FK_COD_CLI INTEGER NOT NULL,
	FOREIGN KEY (FK_COD_END) REFERENCES ENDERECO(COD_END),
	FOREIGN KEY (FK_COD_CLI) REFERENCES CLIENTE(COD_CLI)
)

CREATE TABLE CATEGORIA
(
	COD_CAT INTEGER PRIMARY KEY NOT NULL IDENTITY,
	NOME VARCHAR(60),
	VALOR NUMERIC(15,2)
)
--inclui o identity
CREATE TABLE GENERO
(
	COD_GEN INTEGER NOT NULL PRIMARY KEY identity,
	NOME VARCHAR(60)
)

CREATE TABLE FILMES
(
	COD_FILME INTEGER NOT NULL PRIMARY KEY IDENTITY,
	TITULO_ORIGINAL VARCHAR(100),
	TITULO VARCHAR(100),
	QUANTIDADE INT,
	FK_COD_CAT INTEGER,
	FK_COD_GEN INTEGER,
	FOREIGN KEY (FK_COD_CAT) REFERENCES CATEGORIA(COD_CAT), 
	FOREIGN KEY (FK_COD_GEN) REFERENCES GENERO(COD_GEN)
)
--inclui o identity
CREATE TABLE ATOR
(
	COD_ATOR INTEGER NOT NULL PRIMARY KEY identity,
	NOME VARCHAR(60)
)

CREATE table FILME_ATOR
(
	COD_ATOR INTEGER NOT NULL,
	COD_FILME INTEGER NOT NULL,
	PRIMARY KEY (COD_ATOR, COD_FILME),
	FOREIGN KEY (COD_ATOR) REFERENCES ATOR(COD_ATOR),
	FOREIGN KEY (COD_FILME) REFERENCES FILMES(COD_FILME)
)

CREATE TABLE DEPENDENTE
(
	COD_CLI INTEGER NOT NULL,
	COD_DEP INTEGER NOT NULL,
	PARENTESCO VARCHAR(20),
	PRIMARY KEY  (COD_CLI, COD_DEP),
	FOREIGN KEY (COD_CLI) REFERENCES CLIENTE(COD_CLI),
	FOREIGN KEY (COD_DEP) REFERENCES CLIENTE(COD_CLI)
)
--INCLUI O IDENTITY
CREATE TABLE LOCACAO
(
	COD_LOC INTEGER NOT NULL PRIMARY KEY identity,
	DATA_LOC DATE,
	DESCONTO NUMERIC(15,2),
	MULTA NUMERIC(15,2),
	SUB_TOTAL NUMERIC(15,2),
	FK_COD_CLI INTEGER,
	FOREIGN KEY (FK_COD_CLI) REFERENCES CLIENTE(COD_CLI)
)

CREATE TABLE LOCACAO_FILME
(
	COD_LOC INTEGER NOT NULL,
	COD_FILME INTEGER NOT NULL,
	PRIMARY KEY(COD_LOC,COD_FILME),
	VALOR NUMERIC(15,2),
	NUM_DIAS INT,
	DATA_DEVOL DATE,
	FOREIGN KEY (COD_LOC) REFERENCES LOCACAO(COD_LOC),
	FOREIGN KEY (COD_FILME) REFERENCES FILMES(COD_FILME)
)
SELECT * FROM ATOR
INSERT INTO ATOR VALUES('GABRIEL CRUISE')
INSERT INTO ATOR VALUES('HENRIQUE HANKS')
INSERT INTO ATOR VALUES('LEONARDO DI CAPRIO')
INSERT INTO ATOR VALUES('DOUGLAS CAGE')
INSERT INTO ATOR VALUES('FABRICO TORETO ')
INSERT INTO ATOR VALUES('IGOR PORTIOLI')
INSERT INTO ATOR VALUES('MELISSA BULMAN')
INSERT INTO ATOR VALUES('VICTOR CASTAGNA')
INSERT INTO ATOR VALUES('LARISSA MANUSIN')
INSERT INTO ATOR VALUES('LUCAS GERMANO')

SELECT * FROM CATEGORIA
INSERT INTO CATEGORIA VALUES('CLASSICO', '5')
INSERT INTO CATEGORIA VALUES('PREMIUM', '20')
INSERT INTO CATEGORIA VALUES('LANÇAMENTO', '30')
INSERT INTO CATEGORIA VALUES('CULT', '7')
--linha removida
--INSERT INTO CATEGORIA VALUES('LGBT', '150')
INSERT INTO CATEGORIA VALUES('FAMILIA', '10')


SELECT * FROM ENDERECO
INSERT INTO ENDERECO VALUES ('Barao do Triunfo', 'Rua', 'Terro', 'Santa Maria', 'RS', '97010320', '736', 'Rosario')
INSERT INTO ENDERECO VALUES ('Silva Jardim', 'Rua', 'Ap 101', 'Santa Maria', 'RS', '97010490', '5521', 'Centro')
INSERT INTO ENDERECO VALUES ('Liberdade', 'Avenida', 'Ap 303', 'Santa Maria', 'RS', '97010070', '36', 'Passo da Areia')
INSERT INTO ENDERECO VALUES ('Presidente Vargas', 'Avenida', 'Casa', 'Santa Maria', 'RS', '97010240', '73', 'Centro')
INSERT INTO ENDERECO VALUES ('Venancio Aires', 'Rua', 'Casa', 'Santa Maria', 'RS', '97010250', '66', 'Bom fim')
INSERT INTO ENDERECO VALUES ('Dos Andradas', 'Rua', 'Fundos', 'Santa Maria', 'RS', '97010339', '1736', 'Bom fim')
INSERT INTO ENDERECO VALUES ('Dr Bozano', 'Rua', 'Fundos', 'Santa Maria', 'RS', '97010780', '637', 'Centro')
INSERT INTO ENDERECO VALUES ('Oscar Knackfuus', 'Rua', 'Ap 409', 'Santa Maria', 'RS', '97010445', '376', 'Camobi')
INSERT INTO ENDERECO VALUES ('Conde de Porto Algre', 'Rua', 'Casa', 'Santa Maria', 'RS', '97010800', '1522', 'Perpetuo Socorro')
INSERT INTO ENDERECO VALUES ('Duque de Caxias', 'Rua', 'Casa', 'Santa Maria', 'RS', '97010450', '15', 'Centro')
--inclui duas linhas aqui
INSERT INTO ENDERECO VALUES ('Conde de Porto Algre', 'Rua', 'Ap 120', 'Santa Maria', 'RS', '97010800', '1200', 'Perpetuo Socorro')
INSERT INTO ENDERECO VALUES ('Duque de Caxias', 'Avenida', 'Casa', 'Florianópolis', 'SC', '98010470', '20', 'Centro')

SELECT * FROM PROFISSAO
INSERT INTO PROFISSAO VALUES('Engenheiro Mecânico')
INSERT INTO PROFISSAO VALUES('Astronauta')
INSERT INTO PROFISSAO VALUES('Biologo')
INSERT INTO PROFISSAO VALUES('Bombeiro')
INSERT INTO PROFISSAO VALUES('Policial')
INSERT INTO PROFISSAO VALUES('Programador')
INSERT INTO PROFISSAO VALUES('Jogador de Futebol')
INSERT INTO PROFISSAO VALUES('Artesão')
INSERT INTO PROFISSAO VALUES('Militar')
INSERT INTO PROFISSAO VALUES('Vendedor')


SELECT * FROM CLIENTE
INSERT INTO CLIENTE VALUES('02351259856','Gabriel Diniz','5598251635','1')
INSERT INTO CLIENTE VALUES('59423610587','Lucas Netto','5598422336','2')
INSERT INTO CLIENTE VALUES('22360041230','Yuri Martins','5599961458','3')
INSERT INTO CLIENTE VALUES('00214856325','Fernando Sorocaba','5598456143','4')
INSERT INTO CLIENTE VALUES('11258695347','Zé Neto','5596521439','5')
INSERT INTO CLIENTE VALUES('15975364528','Dinho Ouro','5599152347','6')
INSERT INTO CLIENTE VALUES('32569874105','Humberto Gessinger','5599965451','7')
INSERT INTO CLIENTE VALUES('12365478909','Renato Russo','5599631248','8')
INSERT INTO CLIENTE VALUES('32145698752','João Maria','5598145263','9')
INSERT INTO CLIENTE VALUES('35745695321','Giuliano Gonçalves','5599825463','10')
--inclui duas linhas aqui
INSERT INTO CLIENTE VALUES('15236985470','Sabrina Sato','5599825463','2')
INSERT INTO CLIENTE VALUES('45286000336','Kelly Key','5599825463','5')

SELECT * FROM CLI_ENDERECO
SELECT * FROM CLIENTE
SELECT * FROM ENDERECO
INSERT INTO CLI_ENDERECO VALUES ('1','1')
INSERT INTO CLI_ENDERECO VALUES ('2','2')
INSERT INTO CLI_ENDERECO VALUES ('3','3')
INSERT INTO CLI_ENDERECO VALUES ('4','4')
INSERT INTO CLI_ENDERECO VALUES ('5','5')
INSERT INTO CLI_ENDERECO VALUES ('6','6')
INSERT INTO CLI_ENDERECO VALUES ('7','7')
INSERT INTO CLI_ENDERECO VALUES ('8','8')
INSERT INTO CLI_ENDERECO VALUES ('9','9')
INSERT INTO CLI_ENDERECO VALUES ('10','10')
--inclui duas linhas aqui
INSERT INTO CLI_ENDERECO VALUES ('11','11')
INSERT INTO CLI_ENDERECO VALUES ('12','12')

SELECT * FROM GENERO
INSERT INTO GENERO VALUES ('Romance')
INSERT INTO GENERO VALUES ('Aventura')
INSERT INTO GENERO VALUES ('Ação')
INSERT INTO GENERO VALUES ('Terror')
INSERT INTO GENERO VALUES ('Fantasia')
INSERT INTO GENERO VALUES ('Infantil')
INSERT INTO GENERO VALUES ('Drama')
INSERT INTO GENERO VALUES ('Comédia')
INSERT INTO GENERO VALUES ('Documentário')
INSERT INTO GENERO VALUES ('Ficção')

SELECT * FROM FILMES
SELECT * FROM CATEGORIA
SELECT * FROM GENERO

INSERT INTO FILMES VALUES('The Godfather','O Poderoso Chefão','5','2','3')
INSERT INTO FILMES VALUES('The Hangover','Se beber Não Case','3','5','8')
INSERT INTO FILMES VALUES('Jaws','Tubarão','4','4','3')
INSERT INTO FILMES VALUES('Warm Bodies','Meu namorado é um Zumbi','2','3','1')
INSERT INTO FILMES VALUES('Home Alone','Esqueceram de Mim','8','2','8')
INSERT INTO FILMES VALUES('My Girl','Meu primeiro amor','7','2','1')
INSERT INTO FILMES VALUES('Saw','Jogos Mortais','6','4','4')
INSERT INTO FILMES VALUES('Ferris Buellers Day Off','Curtindo a Vida Adoidado','7','2','8')
INSERT INTO FILMES VALUES('Airplane','Apertem os cintos... O piloto sumiu!','4','4','5')
INSERT INTO FILMES VALUES('Meet The Parents','Entrando Numa Fria','3','3','8')

SELECT * FROM FILME_ATOR
SELECT * FROM ATOR
SELECT * FROM FILMES
--refiz esse insert para mostrar mais dados na hora da consulta
INSERT INTO FILME_ATOR VALUES('1','1')
INSERT INTO FILME_ATOR VALUES('1','5')
INSERT INTO FILME_ATOR VALUES('1','2')
INSERT INTO FILME_ATOR VALUES('2','4')
INSERT INTO FILME_ATOR VALUES('2','3')
INSERT INTO FILME_ATOR VALUES('3','6')
INSERT INTO FILME_ATOR VALUES('3','7')
INSERT INTO FILME_ATOR VALUES('4','8')
INSERT INTO FILME_ATOR VALUES('5','1')
INSERT INTO FILME_ATOR VALUES('5','4')
INSERT INTO FILME_ATOR VALUES('5','5')
INSERT INTO FILME_ATOR VALUES('5','8')
INSERT INTO FILME_ATOR VALUES('5','9')
INSERT INTO FILME_ATOR VALUES('5','10')
INSERT INTO FILME_ATOR VALUES('6','10')
INSERT INTO FILME_ATOR VALUES('7','2')
INSERT INTO FILME_ATOR VALUES('8','1')
INSERT INTO FILME_ATOR VALUES('9','3')
INSERT INTO FILME_ATOR VALUES('10','4')
INSERT INTO FILME_ATOR VALUES('10','9')


SELECT * FROM DEPENDENTE
SELECT * FROM CLIENTE
--refiz esse insert tbm, pois havia somente (pai e filho)
INSERT INTO DEPENDENTE VALUES ('1','12','Mãe')
INSERT INTO DEPENDENTE VALUES ('12','1','Filho')
INSERT INTO DEPENDENTE VALUES ('11','2','Filho')
INSERT INTO DEPENDENTE VALUES ('11','3','Filho')
INSERT INTO DEPENDENTE VALUES ('11','4','Marido')
INSERT INTO DEPENDENTE VALUES ('10','12','Esposa')
INSERT INTO DEPENDENTE VALUES ('9','8','Filho')
INSERT INTO DEPENDENTE VALUES ('7','6','Pai')
INSERT INTO DEPENDENTE VALUES ('3','11','Mãe')
INSERT INTO DEPENDENTE VALUES ('2','11','Mãe')


SELECT * FROM LOCACAO
SELECT * FROM CLIENTE
--incluido mais 7 linhas para mostrar mais dados na consulta
INSERT INTO LOCACAO VALUES ('15/11/2022', '5', '5', '30','1')
INSERT INTO LOCACAO VALUES ('24/02/2022','5','10','40','1')
INSERT INTO LOCACAO VALUES ('30/05/2022','10','0','5','2')
INSERT INTO LOCACAO VALUES ('08/07/2022','10','0','5','2')
INSERT INTO LOCACAO VALUES ('23/08/2022','8','15','50','3')
INSERT INTO LOCACAO VALUES ('17/09/2022','5','0','25','4')
INSERT INTO LOCACAO VALUES ('22/10/2022','5','0','22','5')
INSERT INTO LOCACAO VALUES ('04/01/2022','10','12','27','5')
INSERT INTO LOCACAO VALUES ('16/03/2022','5','0','34','5')
INSERT INTO LOCACAO VALUES ('15/08/2022','5','10','25','6')
INSERT INTO LOCACAO VALUES ('01/01/2022','5','10','25','7')
INSERT INTO LOCACAO VALUES ('15/11/2022','5','15','35','8')
INSERT INTO LOCACAO VALUES ('13/05/2022','5','5','20','9')
INSERT INTO LOCACAO VALUES ('18/06/2022','5','5','25','10')
INSERT INTO LOCACAO VALUES ('23/07/2022','5','0','15','11')
INSERT INTO LOCACAO VALUES ('30/08/2022','5','0','15','12')

SELECT * FROM LOCACAO_FILME
SELECT * FROM LOCACAO
SELECT * FROM FILMES
--valores alterados
INSERT INTO LOCACAO_FILME VALUES('2','1','10','3','22/05/2022')
INSERT INTO LOCACAO_FILME VALUES('4','3','40','4','22/06/2022')
INSERT INTO LOCACAO_FILME VALUES('5','3','25','5','22/06/2022')
INSERT INTO LOCACAO_FILME VALUES('6','4','50','6','22/07/2022')
INSERT INTO LOCACAO_FILME VALUES('7','5','12','2','22/08/2022')
INSERT INTO LOCACAO_FILME VALUES('8','6','5','1','22/10/2022')
INSERT INTO LOCACAO_FILME VALUES('9','7','10','2','22/12/2022')
INSERT INTO LOCACAO_FILME VALUES('10','8','20','3','31/12/2022')
INSERT INTO LOCACAO_FILME VALUES('11','9','50','5','03/03/2022')
INSERT INTO LOCACAO_FILME VALUES('12','10','20','4','04/01/2022')
INSERT INTO LOCACAO_FILME VALUES('13','2','20','3','23/10/2022')
INSERT INTO LOCACAO_FILME VALUES('14','1','40','4','08/11/2022')
INSERT INTO LOCACAO_FILME VALUES('15','3','25','5','06/02/2022')
INSERT INTO LOCACAO_FILME VALUES('16','4','50','6','02/05/2022')
INSERT INTO LOCACAO_FILME VALUES('1','5','10','2','04/03/2022')
INSERT INTO LOCACAO_FILME VALUES('3','6','5','1','01/01/2022')
INSERT INTO LOCACAO_FILME VALUES('3','10','22','2','11/01/2022')
INSERT INTO LOCACAO_FILME VALUES('3','1','25','3','08/04/2022')
INSERT INTO LOCACAO_FILME VALUES('1','3','60','7','02/03/2022')
INSERT INTO LOCACAO_FILME VALUES('2','3','20','4','04/05/2022')
INSERT INTO LOCACAO_FILME VALUES('2','7','20','4','04/02/2022')


-- 1
SELECT
    A.NOME AS Ator,
    F.TITULO AS Filme
FROM ATOR A
LEFT JOIN FILME_ATOR FA ON FA.COD_ATOR = A.COD_ATOR
LEFT JOIN FILMES F ON F.COD_FILME = FA.COD_FILME
ORDER BY A.NOME, F.TITULO;


-- 2 
SELECT
    C.NOME AS Cliente,
    L.COD_LOC,
    L.DATA_LOC,
    F.TITULO AS Filme,
    LF.NUM_DIAS,
    LF.DATA_DEVOL,
    LF.VALOR
FROM CLIENTE C
INNER JOIN LOCACAO L ON L.FK_COD_CLI = C.COD_CLI
INNER JOIN LOCACAO_FILME LF ON LF.COD_LOC = L.COD_LOC
INNER JOIN FILMES F ON F.COD_FILME = LF.COD_FILME
ORDER BY C.NOME, L.DATA_LOC, F.TITULO;


-- 3 
SELECT
    F.TITULO,
    G.NOME AS Genero,
    C.NOME AS Categoria,
    C.VALOR AS ValorCategoria,
    F.QUANTIDADE
FROM FILMES F
INNER JOIN GENERO G ON G.COD_GEN = F.FK_COD_GEN
INNER JOIN CATEGORIA C ON C.COD_CAT = F.FK_COD_CAT
ORDER BY F.TITULO;


-- 4 
SELECT DISTINCT
    L.DATA_LOC,
    Cli.NOME AS Cliente,
    F.TITULO AS Filme
FROM LOCACAO L
INNER JOIN CLIENTE Cli ON Cli.COD_CLI = L.FK_COD_CLI
INNER JOIN LOCACAO_FILME LF ON LF.COD_LOC = L.COD_LOC
INNER JOIN FILMES F ON F.COD_FILME = LF.COD_FILME
WHERE YEAR(L.DATA_LOC) = 2026
ORDER BY L.DATA_LOC, Cli.NOME, F.TITULO;


-- 5 
SELECT TOP (2)
    F.COD_FILME,
    F.TITULO,
    COUNT(*) AS Qtd_Locacoes
FROM LOCACAO L
INNER JOIN LOCACAO_FILME LF ON LF.COD_LOC = L.COD_LOC
INNER JOIN FILMES F ON F.COD_FILME = LF.COD_FILME
WHERE YEAR(L.DATA_LOC) = 2025
GROUP BY F.COD_FILME, F.TITULO
ORDER BY Qtd_Locacoes DESC, F.TITULO;

-- 6
SELECT TOP (1)
    G.NOME AS Genero,
    COUNT(*) AS Qtd_Locacoes
FROM LOCACAO L
INNER JOIN LOCACAO_FILME LF ON LF.COD_LOC = L.COD_LOC
INNER JOIN FILMES F ON F.COD_FILME = LF.COD_FILME
INNER JOIN GENERO G ON G.COD_GEN = F.FK_COD_GEN
GROUP BY G.NOME
ORDER BY Qtd_Locacoes DESC, G.NOME;

-- 7 
SELECT
    E.UF,
    COUNT(DISTINCT C.COD_CLI) AS Qtd_Clientes
FROM CLIENTE C
INNER JOIN CLI_ENDERECO CE ON CE.FK_COD_CLI = C.COD_CLI
INNER JOIN ENDERECO E ON E.COD_END = CE.FK_COD_END
GROUP BY E.UF
ORDER BY Qtd_Clientes DESC, E.UF;

